:development: &dev
  :api_secret: doXOuNTm95VqsX54OnmO
  :multiplier:
    :default: 1
  :game:
    :start_pairs: 4
  :rating:
    :start: 400
    :win: 3
    :lose: -1

:test:
  <<: *dev

:staging:
  <<: *dev

:production:
  <<: *dev
