:development: &dev
  :api_secret: doXOuNTm95VqsX54OnmO
  :url:
    :secret: 6d08487f730835975c0eabb75cc898b2
    :salt: b0b46ecd
  :multiplier:
    :default: 1
  :game:
    :start_pairs: 4
  :rating:
    :start: 400
    :win: 3
    :lose: -1

:test:
  <<: *dev

:staging:
  <<: *dev

:production:
  <<: *dev
